### ISSUE TITLE
No rendering segments

### ISSUE THREAD

**Issue by redeemefy** [MatthewAlner/powerlevel9k-built-with-segment#1]
Hi,

I followed the instructions and this is what I have

- placed `~/.built-with-segment.sh`
- placed `~/built-with-config.json`
- add the line 

```zsh
source ~/.built-with-segment.sh
ZSH_THEME="powerlevel9k/powerlevel9k"
```

Then I `cd` to an angular project and nothing renders. I can't find in the README if I need to add something to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.

**UPDATE**
I got it working. I can create a pr to update README with step-by-step of worked for me and is missing in the README. Let me know if interested.

**Comment by MatthewAlner** [comment]
Hey, that would be great if you have the time thanks

**Comment by redeemefy** [comment]
Open pull request for this issue #2.
